CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    surname    VARCHAR(50)                             NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(50),
    is_active  BOOLEAN,
    created_by BIGINT DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    DROP CONSTRAINT IF EXISTS uc_users_email;

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);