CREATE TABLE IF NOT EXISTS journalists
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    first_name          VARCHAR(100)                            NOT NULL,
    last_name           VARCHAR(100)                            NOT NULL,
    bio                 VARCHAR(500),
    email               VARCHAR(255)                            NOT NULL,
    password            VARCHAR(255)                            NOT NULL,
    profile_picture_url VARCHAR(255),
    joined_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_journalists PRIMARY KEY (id)
);

ALTER TABLE journalists
    DROP CONSTRAINT IF EXISTS uc_journalists_email;

ALTER TABLE journalists
    DROP CONSTRAINT IF EXISTS uc_journalists_user;

ALTER TABLE journalists
    DROP CONSTRAINT IF EXISTS FK_journalists_on_user;

ALTER TABLE journalists
    ADD CONSTRAINT uc_journalists_email UNIQUE (email);

ALTER TABLE journalists
    ADD CONSTRAINT uc_journalists_user UNIQUE (user_id);

ALTER TABLE journalists
    ADD CONSTRAINT FK_JOURNALISTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);