CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(500)                            NOT NULL,
    user_id    BIGINT,
    article_id BIGINT,
    posted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

ALTER TABLE comments
    DROP CONSTRAINT IF EXISTS fk_comments_on_article;

ALTER TABLE comments
    DROP CONSTRAINT IF EXISTS fk_comments_on_user;

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_ARTICLE FOREIGN KEY (article_id) REFERENCES articles (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);